/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.SadClientes;
import dao.SadClientesDAO;
import tools.Sad_Util;

/**
 *
 * @author u70874542189
 */
public class JDlgSad_Clientes extends javax.swing.JDialog {

    private boolean incluir;

    /**
     * Creates new form JDlgSad_Clientes
     */
    public JDlgSad_Clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Confirmar, jBtnSad_Cancelar);
        try {
            javax.swing.text.MaskFormatter mascaraData = new javax.swing.text.MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter(' ');
            jFmtSad_DataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraData));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
    }

    public SadClientes viewBean() {
        SadClientes sadClientes = new SadClientes();
        int codigo = Sad_Util.strToInt(jTxtSad_Codigo.getText());
        sadClientes.setSadIdClientes(codigo);
        sadClientes.setSadNome(jTxtSad_Nome.getText());
        sadClientes.setSadCpf(jFmtSad_Cpf.getText());
        sadClientes.setSadRg(jFmtSad_Rg.getText());
        sadClientes.setSadSexo(jCboSad_Sexo.getSelectedIndex());
        sadClientes.setSadDataNascimento(Sad_Util.strToDate(jFmtSad_DataNascimento.getText()));
        sadClientes.setSadEmail(jTxtSad_Email.getText());
        sadClientes.setSadCep(jFmtSad_Cep.getText());
        sadClientes.setSadEndereco(jTxtSad_Endereco.getText());
        sadClientes.setSadBairro(jTxtSad_Bairro.getText());
        sadClientes.setSadCidade(jTxtSad_Cidade.getText());
        sadClientes.setSadTelefoneResidencial(jFmtSad_Residencial.getText());
        sadClientes.setSadCelular(jFmtSad_Celular.getText());
        sadClientes.setSadSenha(jPwdSad_Senha.getText());
        sadClientes.setSadPronomes(jTxtSad_Pronomes.getText());
        return sadClientes;
    }

    public void beanView(SadClientes sadClientes) {
        jTxtSad_Codigo.setText(Sad_Util.intToStr(sadClientes.getSadIdClientes()));
        jTxtSad_Nome.setText(sadClientes.getSadNome());
        jFmtSad_Cpf.setText(sadClientes.getSadCpf());
        jFmtSad_Rg.setText(sadClientes.getSadRg());
        jCboSad_Sexo.setSelectedIndex(sadClientes.getSadSexo());
        jFmtSad_DataNascimento.setText(Sad_Util.dateToStr(sadClientes.getSadDataNascimento()));
        jTxtSad_Email.setText(sadClientes.getSadEmail());
        jFmtSad_Cep.setText(sadClientes.getSadCep());
        jTxtSad_Endereco.setText(sadClientes.getSadEndereco());
        jTxtSad_Bairro.setText(sadClientes.getSadBairro());
        jTxtSad_Cidade.setText(sadClientes.getSadCidade());
        jFmtSad_Residencial.setText(sadClientes.getSadTelefoneResidencial());
        jFmtSad_Celular.setText(sadClientes.getSadCelular());
        jPwdSad_Senha.setText(sadClientes.getSadSenha());
        jTxtSad_Pronomes.setText(sadClientes.getSadPronomes());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnSad_Confirmar = new javax.swing.JButton();
        jBtnSad_Cancelar = new javax.swing.JButton();
        jBtnSad_Pesquisar = new javax.swing.JButton();
        jBtnSad_Incluir = new javax.swing.JButton();
        jBtnSad_Alterar = new javax.swing.JButton();
        jBtnSad_Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtSad_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtSad_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSad_Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtSad_Cpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtSad_DataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFmtSad_Rg = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jCboSad_Sexo = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jTxtSad_Pronomes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtSad_Endereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtSad_Bairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtSad_Cidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFmtSad_Cep = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jFmtSad_Residencial = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jFmtSad_Celular = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jPwdSad_Senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnSad_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnSad_Confirmar.setText("Confirmar");
        jBtnSad_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ConfirmarActionPerformed(evt);
            }
        });

        jBtnSad_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnSad_Cancelar.setText("Cancelar");
        jBtnSad_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_CancelarActionPerformed(evt);
            }
        });

        jBtnSad_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnSad_Pesquisar.setText("Pesquisar");
        jBtnSad_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_PesquisarActionPerformed(evt);
            }
        });

        jBtnSad_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnSad_Incluir.setText("Incluir");
        jBtnSad_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_IncluirActionPerformed(evt);
            }
        });

        jBtnSad_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnSad_Alterar.setText("Alterar");
        jBtnSad_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_AlterarActionPerformed(evt);
            }
        });

        jBtnSad_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnSad_Excluir.setText("Excluir");
        jBtnSad_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        jLabel3.setText("Email");

        jTxtSad_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSad_EmailActionPerformed(evt);
            }
        });

        jLabel4.setText("Cpf");

        jLabel5.setText("Data de Nascimento");

        jFmtSad_DataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSad_DataNascimentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Rg");

        jLabel7.setText("Sexo");

        jCboSad_Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        jLabel8.setText("Pronomes");

        jLabel9.setText("Endereço");

        jLabel10.setText("Bairro");

        jLabel11.setText("Cidade");

        jLabel12.setText("Cep");

        jLabel13.setText("Telefone Residêncial");

        jLabel14.setText("Celular");

        jLabel15.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jFmtSad_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtSad_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jFmtSad_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCboSad_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtSad_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtSad_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jTxtSad_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFmtSad_Cep)
                                    .addComponent(jTxtSad_Pronomes))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtSad_Residencial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtSad_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPwdSad_Senha)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3)
                            .addComponent(jTxtSad_Email)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtSad_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSad_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Pesquisar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSad_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtSad_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFmtSad_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtSad_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtSad_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboSad_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSad_Pronomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSad_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSad_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSad_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtSad_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtSad_Residencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtSad_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwdSad_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSad_Incluir)
                    .addComponent(jBtnSad_Alterar)
                    .addComponent(jBtnSad_Excluir)
                    .addComponent(jBtnSad_Confirmar)
                    .addComponent(jBtnSad_Cancelar)
                    .addComponent(jBtnSad_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSad_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ConfirmarActionPerformed
        // TODO add your handling code here:
        SadClientesDAO sadClientesDAO = new SadClientesDAO();
        if (incluir) {
            sadClientesDAO.insert(viewBean());
        } else {
            sadClientesDAO.update(viewBean());
        }
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);

    }//GEN-LAST:event_jBtnSad_ConfirmarActionPerformed

    private void jBtnSad_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_CancelarActionPerformed
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_Alterar, jBtnSad_Excluir);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);

    }//GEN-LAST:event_jBtnSad_CancelarActionPerformed

    private void jBtnSad_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgSad_ClientesPesquisar jDlgSad_ClientesPesquisar = new JDlgSad_ClientesPesquisar(null, true);
        jDlgSad_ClientesPesquisar.setTelaPai(this);
        jDlgSad_ClientesPesquisar.setVisible(true);
        if (jDlgSad_ClientesPesquisar.ativarBotoes()) {
            Sad_Util.sad_habilitar(true, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Cancelar);
            Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        }

    }//GEN-LAST:event_jBtnSad_PesquisarActionPerformed

    private void jBtnSad_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_IncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Sad_Util.sad_habilitar(true, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);
        jTxtSad_Codigo.grabFocus();
    }//GEN-LAST:event_jBtnSad_IncluirActionPerformed

    private void jBtnSad_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_AlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Sad_Util.sad_habilitar(true, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(false, jBtnSad_Excluir, jBtnSad_Incluir, jBtnSad_Alterar);
        jTxtSad_Nome.grabFocus();
    }//GEN-LAST:event_jBtnSad_AlterarActionPerformed

    private void jBtnSad_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ExcluirActionPerformed
        // TODO add your handling code here:
        if (Sad_Util.sad_perguntar("Excluir?") == true) {
            SadClientesDAO sadClientesDAO = new SadClientesDAO();
            sadClientesDAO.delete(viewBean());
            Sad_Util.sad_habilitar(false, jBtnSad_Alterar, jBtnSad_Cancelar, jBtnSad_Excluir);
            Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
            Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jTxtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);
        }
    }//GEN-LAST:event_jBtnSad_ExcluirActionPerformed

    private void jTxtSad_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSad_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSad_EmailActionPerformed

    private void jFmtSad_DataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtSad_DataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtSad_DataNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgSad_Clientes dialog = new JDlgSad_Clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSad_Alterar;
    private javax.swing.JButton jBtnSad_Cancelar;
    private javax.swing.JButton jBtnSad_Confirmar;
    private javax.swing.JButton jBtnSad_Excluir;
    private javax.swing.JButton jBtnSad_Incluir;
    private javax.swing.JButton jBtnSad_Pesquisar;
    private javax.swing.JComboBox<String> jCboSad_Sexo;
    private javax.swing.JFormattedTextField jFmtSad_Celular;
    private javax.swing.JFormattedTextField jFmtSad_Cep;
    private javax.swing.JFormattedTextField jFmtSad_Cpf;
    private javax.swing.JFormattedTextField jFmtSad_DataNascimento;
    private javax.swing.JFormattedTextField jFmtSad_Residencial;
    private javax.swing.JFormattedTextField jFmtSad_Rg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPwdSad_Senha;
    private javax.swing.JTextField jTxtSad_Bairro;
    private javax.swing.JTextField jTxtSad_Cidade;
    private javax.swing.JTextField jTxtSad_Codigo;
    private javax.swing.JTextField jTxtSad_Email;
    private javax.swing.JTextField jTxtSad_Endereco;
    private javax.swing.JTextField jTxtSad_Nome;
    private javax.swing.JTextField jTxtSad_Pronomes;
    // End of variables declaration//GEN-END:variables
}
