/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.SadUsuarios;
import dao.SadUsuariosDAO;
import tools.Sad_Util;

/**
 *
 * @author u10916731103
 */
public class JDlgSad_Usuarios extends javax.swing.JDialog {
    
    private boolean incluir;

    public JDlgSad_Usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Confirmar, jBtnSad_Cancelar);
    }
    
    public SadUsuarios viewBean() {
        SadUsuarios sadUsuarios = new SadUsuarios();
        int codigo = Sad_Util.strToInt(jTxtSad_Codigo.getText());
        sadUsuarios.setSadIdUsuarios(codigo);
        sadUsuarios.setSadNome(jTxtSad_Nome.getText());
        sadUsuarios.setSadApelido(jTxtSad_Apelido.getText());
        sadUsuarios.setSadCpf(jFmtSad_Cpf.getText());
        sadUsuarios.setSadSenha(jPwdSad_Senha.getText());
        sadUsuarios.setSadNivel(jCboSad_Nivel.getSelectedIndex());
        sadUsuarios.setSadAtivo(jChbSad_Ativo.isSelected() ? "S" : "N");
        sadUsuarios.setSadDataNascimento(Sad_Util.strToDate(jFmtSad_DataNascimento.getText()));
        return sadUsuarios;
    }
    
    public void beanView(SadUsuarios sadUsuarios) {
        jTxtSad_Codigo.setText(Sad_Util.intToStr(sadUsuarios.getSadIdUsuarios()));
        jTxtSad_Nome.setText(sadUsuarios.getSadNome());
        jTxtSad_Apelido.setText(sadUsuarios.getSadApelido());
        jFmtSad_Cpf.setText(sadUsuarios.getSadCpf());
        jPwdSad_Senha.setText(sadUsuarios.getSadSenha());
        jCboSad_Nivel.setSelectedIndex(sadUsuarios.getSadNivel());
        jChbSad_Ativo.setSelected("S".equals(sadUsuarios.getSadAtivo()));
        jFmtSad_DataNascimento.setText(Sad_Util.dateToStr(sadUsuarios.getSadDataNascimento()));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtSad_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtSad_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSad_Apelido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtSad_Cpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtSad_DataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPwdSad_Senha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jChbSad_Ativo = new javax.swing.JCheckBox();
        jCboSad_Nivel = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jBtnSad_Incluir = new javax.swing.JButton();
        jBtnSad_Alterar = new javax.swing.JButton();
        jBtnSad_Excluir = new javax.swing.JButton();
        jBtnSad_Confirmar = new javax.swing.JButton();
        jBtnSad_Cancelar = new javax.swing.JButton();
        jBtnSad_Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jTxtSad_Codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtSad_CodigoFocusLost(evt);
            }
        });

        jLabel2.setText("Nome");

        jTxtSad_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSad_NomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Apelido");

        jLabel4.setText("CPF");

        jLabel5.setText("Data de Nascimento");

        jLabel6.setText("Senha");

        jLabel7.setText("Nível");

        jCboSad_Nivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "administrador", "funcionario", "vendedor", "gerente" }));
        jCboSad_Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSad_NivelActionPerformed(evt);
            }
        });

        jLabel8.setText("Ativo");

        jBtnSad_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnSad_Incluir.setText("Incluir");
        jBtnSad_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_IncluirActionPerformed(evt);
            }
        });

        jBtnSad_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnSad_Alterar.setText("Alterar");
        jBtnSad_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_AlterarActionPerformed(evt);
            }
        });

        jBtnSad_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnSad_Excluir.setText("Excluir");
        jBtnSad_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ExcluirActionPerformed(evt);
            }
        });

        jBtnSad_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnSad_Confirmar.setText("Confirmar");
        jBtnSad_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ConfirmarActionPerformed(evt);
            }
        });

        jBtnSad_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnSad_Cancelar.setText("Cancelar");
        jBtnSad_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_CancelarActionPerformed(evt);
            }
        });

        jBtnSad_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnSad_Pesquisar.setText("Pesquisar");
        jBtnSad_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPwdSad_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(jFmtSad_Cpf))
                                    .addComponent(jLabel6))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jCboSad_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtSad_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jChbSad_Ativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jTxtSad_Nome)
                    .addComponent(jTxtSad_Apelido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnSad_Incluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Confirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Pesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtSad_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtSad_Apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtSad_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtSad_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChbSad_Ativo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPwdSad_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCboSad_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSad_Incluir)
                    .addComponent(jBtnSad_Alterar)
                    .addComponent(jBtnSad_Excluir)
                    .addComponent(jBtnSad_Confirmar)
                    .addComponent(jBtnSad_Cancelar)
                    .addComponent(jBtnSad_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtSad_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSad_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSad_NomeActionPerformed

    private void jBtnSad_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_IncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Sad_Util.sad_habilitar(true, jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento);
        jFmtSad_DataNascimento.setText(Sad_Util.dateToStr(new java.util.Date()));
        jTxtSad_Codigo.grabFocus();

    }//GEN-LAST:event_jBtnSad_IncluirActionPerformed

    private void jBtnSad_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_AlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Sad_Util.sad_habilitar(true, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(false, jBtnSad_Excluir, jBtnSad_Incluir, jBtnSad_Alterar);
        jTxtSad_Nome.grabFocus();

    }//GEN-LAST:event_jBtnSad_AlterarActionPerformed

    private void jBtnSad_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ExcluirActionPerformed
        // TODO add your handling code here:
        if (Sad_Util.sad_perguntar("Excluir?") == true) {
            SadUsuariosDAO sadUsuariosDAO = new SadUsuariosDAO();
            sadUsuariosDAO.delete(viewBean());
            Sad_Util.sad_habilitar(false, jBtnSad_Alterar, jBtnSad_Cancelar, jBtnSad_Excluir);
            Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);           
            Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento);
        }
    }//GEN-LAST:event_jBtnSad_ExcluirActionPerformed


    private void jBtnSad_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ConfirmarActionPerformed
        // TODO add your handling code here:
        SadUsuariosDAO sadUsuariosDAO = new SadUsuariosDAO();
        if(incluir) {
            sadUsuariosDAO.insert(viewBean());
        } else {
            sadUsuariosDAO.update(viewBean());
        }
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento);

    }//GEN-LAST:event_jBtnSad_ConfirmarActionPerformed

    private void jBtnSad_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgSad_UsuariosPesquisar jDlgSad_UsuariosPesquisar = new JDlgSad_UsuariosPesquisar(null, true);
        jDlgSad_UsuariosPesquisar.setTelaPai(this);
        jDlgSad_UsuariosPesquisar.setVisible(true);
        if (jDlgSad_UsuariosPesquisar.ativarBotoes()) {
            Sad_Util.sad_habilitar(true, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Cancelar);
            Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        }


    }//GEN-LAST:event_jBtnSad_PesquisarActionPerformed

    private void jBtnSad_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_CancelarActionPerformed
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_Alterar, jBtnSad_Excluir);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jPwdSad_Senha, jCboSad_Nivel, jChbSad_Ativo, jTxtSad_Apelido, jFmtSad_Cpf, jFmtSad_DataNascimento);

    }//GEN-LAST:event_jBtnSad_CancelarActionPerformed

    private void jTxtSad_CodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtSad_CodigoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtSad_CodigoFocusLost

    private void jCboSad_NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboSad_NivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboSad_NivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgSad_Usuarios dialog = new JDlgSad_Usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSad_Alterar;
    private javax.swing.JButton jBtnSad_Cancelar;
    private javax.swing.JButton jBtnSad_Confirmar;
    private javax.swing.JButton jBtnSad_Excluir;
    private javax.swing.JButton jBtnSad_Incluir;
    private javax.swing.JButton jBtnSad_Pesquisar;
    private javax.swing.JComboBox<String> jCboSad_Nivel;
    private javax.swing.JCheckBox jChbSad_Ativo;
    private javax.swing.JFormattedTextField jFmtSad_Cpf;
    private javax.swing.JFormattedTextField jFmtSad_DataNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPwdSad_Senha;
    private javax.swing.JTextField jTxtSad_Apelido;
    private javax.swing.JTextField jTxtSad_Codigo;
    private javax.swing.JTextField jTxtSad_Nome;
    // End of variables declaration//GEN-END:variables
}
