/*//GEN-FIRST:event_jCboSad_SexoActionPerformed
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license//GEN-LAST:event_jCboSad_SexoActionPerformed
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Sad_Util;

/**
 *
 * @author SANTIAGO
 */
public class JDlgSad_Clientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgSad_Clientes
     */
    public JDlgSad_Clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar , jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Confirmar, jBtnSad_Cancelar );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtSad_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtSad_Nome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jFmtSad_Rg = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSad_Email = new javax.swing.JTextField();
        jFmtSad_Cpf = new javax.swing.JFormattedTextField();
        jFmtSad_DataNascimento = new javax.swing.JFormattedTextField();
        jFmtSad_Pronomes = new javax.swing.JFormattedTextField();
        jCboSad_Sexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtSad_Endereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtSad_Cidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtSad_Bairro = new javax.swing.JTextField();
        jFmtSad_Cep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFmtSad_Residencial = new javax.swing.JFormattedTextField();
        jFmtSad_Celular = new javax.swing.JFormattedTextField();
        jPwdSad_Senha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jBtnSad_Cancelar = new javax.swing.JButton();
        jBtnSad_Pesquisar = new javax.swing.JButton();
        jBtnSad_Incluir = new javax.swing.JButton();
        jBtnSad_Alterar = new javax.swing.JButton();
        jBtnSad_Excluir = new javax.swing.JButton();
        jBtnSad_Confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        jLabel15.setText("Pronomes");

        jLabel3.setText("Email");

        jFmtSad_Cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSad_CpfActionPerformed(evt);
            }
        });

        jFmtSad_DataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSad_DataNascimentoActionPerformed(evt);
            }
        });

        jCboSad_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jCboSad_Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSad_SexoActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        jLabel5.setText("Data de Nascimento");

        jLabel7.setText("Sexo");

        jLabel8.setText("Rg");

        jLabel11.setText("Bairro");

        jLabel12.setText("Cidade");

        jLabel10.setText("Endereço");

        jFmtSad_Cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSad_CepActionPerformed(evt);
            }
        });

        jLabel9.setText("Cep");

        jLabel13.setText("Telefone Residêncial");

        jLabel14.setText("Celular");

        jFmtSad_Residencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSad_ResidencialActionPerformed(evt);
            }
        });

        jFmtSad_Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSad_CelularActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha");

        jBtnSad_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnSad_Cancelar.setText("Cancelar");
        jBtnSad_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_CancelarActionPerformed(evt);
            }
        });

        jBtnSad_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnSad_Pesquisar.setText("Pesquisar");
        jBtnSad_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_PesquisarActionPerformed(evt);
            }
        });

        jBtnSad_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnSad_Incluir.setText("Incluir");
        jBtnSad_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_IncluirActionPerformed(evt);
            }
        });

        jBtnSad_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnSad_Alterar.setText("Alterar");
        jBtnSad_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_AlterarActionPerformed(evt);
            }
        });

        jBtnSad_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnSad_Excluir.setText("Excluir");
        jBtnSad_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ExcluirActionPerformed(evt);
            }
        });

        jBtnSad_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnSad_Confirmar.setText("Confirmar");
        jBtnSad_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jFmtSad_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFmtSad_DataNascimento)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFmtSad_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(135, 135, 135)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jCboSad_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap())
                    .addComponent(jFmtSad_Pronomes)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTxtSad_Email)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtSad_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(39, 39, 39)
                            .addComponent(jLabel2))))
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtSad_Endereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtSad_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtSad_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jFmtSad_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmtSad_Residencial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtSad_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPwdSad_Senha))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel14)
                                .addGap(172, 172, 172)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSad_Incluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSad_Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSad_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSad_Confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSad_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSad_Pesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSad_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSad_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFmtSad_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFmtSad_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCboSad_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFmtSad_Pronomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtSad_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtSad_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSad_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtSad_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtSad_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtSad_Residencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtSad_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwdSad_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSad_Incluir)
                    .addComponent(jBtnSad_Alterar)
                    .addComponent(jBtnSad_Excluir)
                    .addComponent(jBtnSad_Confirmar)
                    .addComponent(jBtnSad_Cancelar)
                    .addComponent(jBtnSad_Pesquisar))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jFmtSad_CpfActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jFmtSad_DataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void jCboSad_SexoActionPerformed(java.awt.event.ActionEvent evt) {                                             

    }                                            

    private void jFmtSad_CepActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jFmtSad_ResidencialActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jFmtSad_CelularActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jBtnSad_CancelarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_Alterar, jBtnSad_Excluir );
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);
    }                                                

    private void jBtnSad_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        Sad_Util.sad_mensagem("Você pesquisou");
        Sad_Util.sad_habilitar(true, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(false,jBtnSad_Incluir, jBtnSad_Pesquisar);
        
    }                                                 

    private void jBtnSad_IncluirActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(true, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar );
        Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);

    }                                               

    private void jBtnSad_AlterarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(true, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar );
        Sad_Util.sad_habilitar(false,jBtnSad_Excluir, jBtnSad_Incluir, jBtnSad_Alterar);

    }                                               

    private void jBtnSad_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        if(Sad_Util.sad_perguntar("Excluir?")){
            Sad_Util.sad_habilitar(false, jBtnSad_Alterar, jBtnSad_Cancelar, jBtnSad_Excluir);
            Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
            Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);
        }
    }                                               

    private void jBtnSad_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha, jBtnSad_Confirmar, jBtnSad_Cancelar );
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Email, jFmtSad_Rg, jCboSad_Sexo, jFmtSad_Pronomes, jTxtSad_Endereco, jFmtSad_Cpf, jFmtSad_DataNascimento, jTxtSad_Bairro, jTxtSad_Cidade, jFmtSad_Cep, jFmtSad_Residencial, jFmtSad_Celular, jPwdSad_Senha);
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgSad_Clientes dialog = new JDlgSad_Clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBtnSad_Alterar;
    private javax.swing.JButton jBtnSad_Cancelar;
    private javax.swing.JButton jBtnSad_Confirmar;
    private javax.swing.JButton jBtnSad_Excluir;
    private javax.swing.JButton jBtnSad_Incluir;
    private javax.swing.JButton jBtnSad_Pesquisar;
    private javax.swing.JComboBox<String> jCboSad_Sexo;
    private javax.swing.JFormattedTextField jFmtSad_Celular;
    private javax.swing.JFormattedTextField jFmtSad_Cep;
    private javax.swing.JFormattedTextField jFmtSad_Cpf;
    private javax.swing.JFormattedTextField jFmtSad_DataNascimento;
    private javax.swing.JFormattedTextField jFmtSad_Pronomes;
    private javax.swing.JFormattedTextField jFmtSad_Residencial;
    private javax.swing.JFormattedTextField jFmtSad_Rg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPwdSad_Senha;
    private javax.swing.JTextField jTxtSad_Bairro;
    private javax.swing.JTextField jTxtSad_Cidade;
    private javax.swing.JTextField jTxtSad_Codigo;
    private javax.swing.JTextField jTxtSad_Email;
    private javax.swing.JTextField jTxtSad_Endereco;
    private javax.swing.JTextField jTxtSad_Nome;
    // End of variables declaration                   
}
