/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Sad_ControllerVendaProdutos;
import pesquisar.JDlgSad_VendasPesquisar;
import bean.SadClientes;
import bean.SadVendaProdutos;
import dao.SadClientesDAO;
import bean.SadVendas;
import dao.SadVendasDAO;
import bean.SadVendedor;
import dao.SadVendaProdutosDAO;
import dao.SadVendedorDAO;
import java.util.ArrayList;
import java.util.List;
import tools.Sad_Util;

/**
 *
 * @author u70874542189
 */
public class JDlgSad_Vendas extends javax.swing.JDialog {

    Sad_ControllerVendaProdutos sad_ControllerVendaProdutos;

    private boolean incluir;

    /**
     * Creates new form JDlgSad_Vendas
     */
    public JDlgSad_Vendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendas");
        setLocationRelativeTo(null);
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_IncluirProd, jBtnSad_AlterarProd, jBtnSad_ExcluirProd);
        SadClientesDAO clientesDAO = new SadClientesDAO();
        SadVendedorDAO vendedoresDAO = new SadVendedorDAO();
        List lista = (List) clientesDAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
            jCboSad_Clientes.addItem((SadClientes) lista.get(i));

        }
        List listaVend = (List) vendedoresDAO.listAll();
        for (Object object : listaVend) {
            jCboSad_Vendedor.addItem((SadVendedor) object);
        }
        try {
            javax.swing.text.MaskFormatter mascaraData = new javax.swing.text.MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter(' ');
            jFmtSad_DataVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraData));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        try {
            javax.swing.text.MaskFormatter mascaraData = new javax.swing.text.MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter(' ');
            jFmtSad_DataVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraData));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        sad_ControllerVendaProdutos = new Sad_ControllerVendaProdutos();
        sad_ControllerVendaProdutos.setList(new ArrayList());
        jTblSad_Tabela.setModel(sad_ControllerVendaProdutos);
    }

    public SadVendas viewBean() {
        SadVendas sadVendas = new SadVendas();
        int codigo = Sad_Util.strToInt(jTxtSad_Codigo.getText());
        sadVendas.setSadIdVendas(codigo);
        sadVendas.setSadClientes((SadClientes) jCboSad_Clientes.getSelectedItem());
        sadVendas.setSadVendedor((SadVendedor) jCboSad_Vendedor.getSelectedItem());
        sadVendas.setSadDataVendas(Sad_Util.strToDate(jFmtSad_DataVendas.getText()));
        sadVendas.setSadTotal(Sad_Util.strToDouble(jTxtSad_Total.getText()));
        return sadVendas;
    }

    public void beanView(SadVendas sadVendas) {
        jTxtSad_Codigo.setText(Sad_Util.intToStr(sadVendas.getSadIdVendas()));
        jCboSad_Clientes.setSelectedItem(sadVendas.getSadClientes());
        jCboSad_Vendedor.setSelectedItem(sadVendas.getSadVendedor());
        jFmtSad_DataVendas.setText(Sad_Util.dateToStr(sadVendas.getSadDataVendas()));
        jTxtSad_Total.setText(Sad_Util.doubleToStr(sadVendas.getSadTotal()));
        SadVendaProdutosDAO sadVendaProdutosDAO = new SadVendaProdutosDAO();
        List lista = (List) sadVendaProdutosDAO.listProdutos(sadVendas);
        sad_ControllerVendaProdutos.setList(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPanelSad_Painel = new javax.swing.JScrollPane();
        jTblSad_Tabela = new javax.swing.JTable();
        jCboSad_Clientes = new javax.swing.JComboBox<SadClientes>();
        jLabel1 = new javax.swing.JLabel();
        jCboSad_Vendedor = new javax.swing.JComboBox<SadVendedor>();
        jTxtSad_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtSad_Total = new javax.swing.JTextField();
        jFmtSad_DataVendas = new javax.swing.JFormattedTextField();
        jBtnSad_Confirmar = new javax.swing.JButton();
        jBtnSad_Cancelar = new javax.swing.JButton();
        jBtnSad_Pesquisar = new javax.swing.JButton();
        jBtnSad_Incluir = new javax.swing.JButton();
        jBtnSad_Alterar = new javax.swing.JButton();
        jBtnSad_Excluir = new javax.swing.JButton();
        jBtnSad_IncluirProd = new javax.swing.JButton();
        jBtnSad_AlterarProd = new javax.swing.JButton();
        jBtnSad_ExcluirProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Clientes");

        jLabel5.setText("Data Vendas");

        jLabel7.setText("Vendedor");

        jTblSad_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelSad_Painel.setViewportView(jTblSad_Tabela);

        jCboSad_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSad_ClientesActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jTxtSad_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSad_CodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        jFmtSad_DataVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSad_DataVendasActionPerformed(evt);
            }
        });

        jBtnSad_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnSad_Confirmar.setText("Confirmar");
        jBtnSad_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ConfirmarActionPerformed(evt);
            }
        });

        jBtnSad_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnSad_Cancelar.setText("Cancelar");
        jBtnSad_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_CancelarActionPerformed(evt);
            }
        });

        jBtnSad_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnSad_Pesquisar.setText("Pesquisar");
        jBtnSad_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_PesquisarActionPerformed(evt);
            }
        });

        jBtnSad_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnSad_Incluir.setText("Incluir");
        jBtnSad_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_IncluirActionPerformed(evt);
            }
        });

        jBtnSad_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnSad_Alterar.setText("Alterar");
        jBtnSad_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_AlterarActionPerformed(evt);
            }
        });

        jBtnSad_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnSad_Excluir.setText("Excluir");
        jBtnSad_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ExcluirActionPerformed(evt);
            }
        });

        jBtnSad_IncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnSad_IncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_IncluirProdActionPerformed(evt);
            }
        });

        jBtnSad_AlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnSad_AlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_AlterarProdActionPerformed(evt);
            }
        });

        jBtnSad_ExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnSad_ExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSad_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSad_Pesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jCboSad_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jCboSad_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtSad_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFmtSad_DataVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPanelSad_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSad_IncluirProd)
                                .addContainerGap(40, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnSad_ExcluirProd)
                                    .addComponent(jBtnSad_AlterarProd))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCboSad_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboSad_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtSad_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtSad_DataVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanelSad_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnSad_IncluirProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSad_AlterarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSad_ExcluirProd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSad_Incluir)
                    .addComponent(jBtnSad_Alterar)
                    .addComponent(jBtnSad_Excluir)
                    .addComponent(jBtnSad_Confirmar)
                    .addComponent(jBtnSad_Cancelar)
                    .addComponent(jBtnSad_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboSad_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboSad_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboSad_ClientesActionPerformed

    private void jTxtSad_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSad_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSad_CodigoActionPerformed

    private void jFmtSad_DataVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtSad_DataVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtSad_DataVendasActionPerformed

    private void jBtnSad_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ConfirmarActionPerformed
        // TODO add your handling code here:
        SadVendasDAO sadVendasDAO = new SadVendasDAO();
        SadVendaProdutosDAO vendaProdutosDAO = new SadVendaProdutosDAO();
        SadVendas venda = viewBean();
        if (incluir == true) {
            sadVendasDAO.insert(venda);
            for (int ind = 0; ind < jTblSad_Tabela.getRowCount(); ind++) {
                SadVendaProdutos vendaProdutos = sad_ControllerVendaProdutos.getBean(ind);
                vendaProdutos.setSadVendas(venda);
                vendaProdutosDAO.insert(vendaProdutos);
            }
        } else {
            sadVendasDAO.update(venda);

        }
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_IncluirProd, jBtnSad_AlterarProd, jBtnSad_ExcluirProd);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas);
    }//GEN-LAST:event_jBtnSad_ConfirmarActionPerformed

    private void jBtnSad_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_CancelarActionPerformed
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_IncluirProd, jBtnSad_AlterarProd, jBtnSad_ExcluirProd);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas);
    }//GEN-LAST:event_jBtnSad_CancelarActionPerformed

    private void jBtnSad_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgSad_VendasPesquisar jDlgSad_VendasPesquisar = new JDlgSad_VendasPesquisar(null, true);
        jDlgSad_VendasPesquisar.setTelaPai(this);
        jDlgSad_VendasPesquisar.setVisible(true);
        if (jDlgSad_VendasPesquisar.ativarBotoes()) {
            Sad_Util.sad_habilitar(true, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Cancelar);
            Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        }

    }//GEN-LAST:event_jBtnSad_PesquisarActionPerformed

    private void jBtnSad_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_IncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Sad_Util.sad_habilitar(true, jTxtSad_Codigo, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_IncluirProd, jBtnSad_AlterarProd, jBtnSad_ExcluirProd);
        Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas);
        jTxtSad_Codigo.grabFocus();
    }//GEN-LAST:event_jBtnSad_IncluirActionPerformed

    private void jBtnSad_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_AlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Sad_Util.sad_habilitar(true, jTxtSad_Total, jFmtSad_DataVendas, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_IncluirProd, jBtnSad_AlterarProd, jBtnSad_ExcluirProd);
        Sad_Util.sad_habilitar(false, jBtnSad_Excluir, jBtnSad_Incluir, jBtnSad_Alterar);
        jTxtSad_Total.grabFocus();
    }//GEN-LAST:event_jBtnSad_AlterarActionPerformed

    private void jBtnSad_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ExcluirActionPerformed
        // TODO add your handling code here:
        if (Sad_Util.sad_perguntar("Excluir?") == true) {
            SadVendasDAO sadVendasDAO = new SadVendasDAO();
            SadVendaProdutosDAO vendaProdutosDAO = new SadVendaProdutosDAO();
            SadVendas venda = viewBean();
            sadVendasDAO.delete(venda);
            for (int ind = 0; ind < jTblSad_Tabela.getRowCount(); ind++) {
                SadVendaProdutos vendaProdutos = sad_ControllerVendaProdutos.getBean(ind);
                vendaProdutos.setSadVendas(venda);
                vendaProdutosDAO.delete(vendaProdutos);
            }
            sadVendasDAO.delete(venda);
            Sad_Util.sad_habilitar(false, jBtnSad_Alterar, jBtnSad_Cancelar, jBtnSad_Excluir);
            Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
            Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Codigo, jTxtSad_Total, jCboSad_Clientes, jCboSad_Vendedor, jFmtSad_DataVendas);
        }
    }//GEN-LAST:event_jBtnSad_ExcluirActionPerformed

    private void jBtnSad_IncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_IncluirProdActionPerformed
        // TODO add your handling code here:
        JDlgSad_VendaProdutos jDlgSad_VendaProdutos = new JDlgSad_VendaProdutos(null, true);
        jDlgSad_VendaProdutos.setTelaPai(this);
        jDlgSad_VendaProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnSad_IncluirProdActionPerformed

    private void jBtnSad_AlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_AlterarProdActionPerformed
        // TODO add your handling code here:
        JDlgSad_VendaProdutos jDlgSad_VendaProdutos = new JDlgSad_VendaProdutos(null, true);
        jDlgSad_VendaProdutos.setTelaPai(this);
        jDlgSad_VendaProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnSad_AlterarProdActionPerformed

    private void jBtnSad_ExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ExcluirProdActionPerformed
        // TODO add your handling code here:
        if (Sad_Util.sad_perguntar("Deseja excluir o produto ?") == true) {
            int rowindex = jTblSad_Tabela.getSelectedRow();
            sad_ControllerVendaProdutos.removeBean(rowindex);
        }
    }//GEN-LAST:event_jBtnSad_ExcluirProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgSad_Vendas dialog = new JDlgSad_Vendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSad_Alterar;
    private javax.swing.JButton jBtnSad_AlterarProd;
    private javax.swing.JButton jBtnSad_Cancelar;
    private javax.swing.JButton jBtnSad_Confirmar;
    private javax.swing.JButton jBtnSad_Excluir;
    private javax.swing.JButton jBtnSad_ExcluirProd;
    private javax.swing.JButton jBtnSad_Incluir;
    private javax.swing.JButton jBtnSad_IncluirProd;
    private javax.swing.JButton jBtnSad_Pesquisar;
    private javax.swing.JComboBox<SadClientes> jCboSad_Clientes;
    private javax.swing.JComboBox<SadVendedor> jCboSad_Vendedor;
    private javax.swing.JFormattedTextField jFmtSad_DataVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPanelSad_Painel;
    private javax.swing.JTable jTblSad_Tabela;
    private javax.swing.JTextField jTxtSad_Codigo;
    private javax.swing.JTextField jTxtSad_Total;
    // End of variables declaration//GEN-END:variables
}
