/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import pesquisar.JDlgSad_ProdutosPesquisar;
import tools.Sad_Util;
import bean.SadProdutos;
import dao.SadProdutosDAO;

/**
 *
 * @author SANTIAGO
 */
public class JDlgSad_Produtos extends javax.swing.JDialog {

    private boolean incluir;

    /**
     * Creates new form JDlgSad_Produtos
     */
    public JDlgSad_Produtos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Confirmar, jBtnSad_Cancelar);
    }

    public SadProdutos viewBean() {
        SadProdutos sadProdutos = new SadProdutos();
        int codigo = Sad_Util.strToInt(jTxtSad_Codigo.getText());
        sadProdutos.setSadIdProdutos(codigo);
        sadProdutos.setSadPeso(jTxtSad_Peso.getText());
        sadProdutos.setSadValor(Sad_Util.strToDouble(jTxtSad_Valor.getText()));
        sadProdutos.setSadNome(jTxtSad_Nome.getText());
        sadProdutos.setSadTestado(jChbSad_Testado.isSelected() ? "S" : "N");
        sadProdutos.setSadNovo(jChbSad_Novo.isSelected() ? "S" : "N");
        sadProdutos.setSadMarca(jTxtSad_Marca.getText());
        return sadProdutos;
    }

    public void beanView(SadProdutos sadProdutos) {
        jTxtSad_Codigo.setText(Sad_Util.intToStr(sadProdutos.getSadIdProdutos()));
        jTxtSad_Peso.setText(sadProdutos.getSadPeso());
        jTxtSad_Valor.setText(Sad_Util.doubleToStr(sadProdutos.getSadValor()));
        jTxtSad_Nome.setText(sadProdutos.getSadNome());
        jChbSad_Testado.setSelected("S".equals(sadProdutos.getSadTestado()));
        jChbSad_Novo.setSelected("S".equals(sadProdutos.getSadNovo()));
        jTxtSad_Marca.setText(sadProdutos.getSadMarca());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtSad_Marca = new javax.swing.JTextField();
        jChbSad_Novo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jChbSad_Testado = new javax.swing.JCheckBox();
        jTxtSad_Valor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtSad_Peso = new javax.swing.JTextField();
        jTxtSad_Codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtSad_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnSad_Incluir = new javax.swing.JButton();
        jBtnSad_Alterar = new javax.swing.JButton();
        jBtnSad_Excluir = new javax.swing.JButton();
        jBtnSad_Confirmar = new javax.swing.JButton();
        jBtnSad_Cancelar = new javax.swing.JButton();
        jBtnSad_Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jChbSad_Novo.setText("Novo");
        jChbSad_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbSad_NovoActionPerformed(evt);
            }
        });

        jLabel4.setText("Peso");

        jLabel5.setText("Valor");

        jChbSad_Testado.setText("Testado");

        jLabel1.setText("Codigo");

        jTxtSad_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSad_PesoActionPerformed(evt);
            }
        });

        jLabel6.setText("Kg");

        jLabel2.setText("Nome");

        jLabel3.setText("Marca");

        jBtnSad_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnSad_Incluir.setText("Incluir");
        jBtnSad_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_IncluirActionPerformed(evt);
            }
        });

        jBtnSad_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnSad_Alterar.setText("Alterar");
        jBtnSad_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_AlterarActionPerformed(evt);
            }
        });

        jBtnSad_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnSad_Excluir.setText("Excluir");
        jBtnSad_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ExcluirActionPerformed(evt);
            }
        });

        jBtnSad_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnSad_Confirmar.setText("Confirmar");
        jBtnSad_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ConfirmarActionPerformed(evt);
            }
        });

        jBtnSad_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnSad_Cancelar.setText("Cancelar");
        jBtnSad_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_CancelarActionPerformed(evt);
            }
        });

        jBtnSad_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnSad_Pesquisar.setText("Pesquisar");
        jBtnSad_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSad_Nome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtSad_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtSad_Peso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel2)))
                                .addGap(62, 62, 62)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtSad_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbSad_Testado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbSad_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnSad_Incluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Confirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSad_Pesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSad_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSad_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSad_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSad_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtSad_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbSad_Testado)
                    .addComponent(jChbSad_Novo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSad_Incluir)
                    .addComponent(jBtnSad_Alterar)
                    .addComponent(jBtnSad_Excluir)
                    .addComponent(jBtnSad_Confirmar)
                    .addComponent(jBtnSad_Cancelar)
                    .addComponent(jBtnSad_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChbSad_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbSad_NovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbSad_NovoActionPerformed

    private void jTxtSad_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSad_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSad_PesoActionPerformed

    private void jBtnSad_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_IncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Sad_Util.sad_habilitar(true, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo);
        jTxtSad_Codigo.grabFocus();
    }//GEN-LAST:event_jBtnSad_IncluirActionPerformed

    private void jBtnSad_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_AlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Sad_Util.sad_habilitar(true, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(false, jBtnSad_Excluir, jBtnSad_Incluir, jBtnSad_Alterar);
        jTxtSad_Nome.grabFocus();
    }//GEN-LAST:event_jBtnSad_AlterarActionPerformed

    private void jBtnSad_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ExcluirActionPerformed
        // TODO add your handling code here:
        if (Sad_Util.sad_perguntar("Excluir?") == true) {
            SadProdutosDAO sadProdutosDAO = new SadProdutosDAO();
            sadProdutosDAO.delete(viewBean());
            Sad_Util.sad_habilitar(false, jBtnSad_Alterar, jBtnSad_Cancelar, jBtnSad_Excluir);
            Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
            Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo);
        }
    }//GEN-LAST:event_jBtnSad_ExcluirActionPerformed

    private void jBtnSad_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ConfirmarActionPerformed
        // TODO add your handling code here:
        SadProdutosDAO sadProdutosDAO = new SadProdutosDAO();
        if (incluir) {
            sadProdutosDAO.insert(viewBean());
        } else {
            sadProdutosDAO.update(viewBean());
        }
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo, jBtnSad_Confirmar, jBtnSad_Cancelar);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo);
    }//GEN-LAST:event_jBtnSad_ConfirmarActionPerformed

    private void jBtnSad_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_CancelarActionPerformed
        // TODO add your handling code here:
        Sad_Util.sad_habilitar(false, jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo, jBtnSad_Confirmar, jBtnSad_Cancelar, jBtnSad_Alterar, jBtnSad_Excluir);
        Sad_Util.sad_habilitar(true, jBtnSad_Incluir, jBtnSad_Pesquisar);
        Sad_Util.sad_limpar(jTxtSad_Codigo, jTxtSad_Nome, jTxtSad_Marca, jTxtSad_Peso, jTxtSad_Valor, jChbSad_Testado, jChbSad_Novo);
    }//GEN-LAST:event_jBtnSad_CancelarActionPerformed

    private void jBtnSad_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgSad_ProdutosPesquisar jDlgSad_ProdutosPesquisar = new JDlgSad_ProdutosPesquisar(null, true);
        jDlgSad_ProdutosPesquisar.setTelaPai(this);
        jDlgSad_ProdutosPesquisar.setVisible(true);
        if (jDlgSad_ProdutosPesquisar.ativarBotoes()) {
            Sad_Util.sad_habilitar(true, jBtnSad_Alterar, jBtnSad_Excluir, jBtnSad_Cancelar);
            Sad_Util.sad_habilitar(false, jBtnSad_Incluir, jBtnSad_Pesquisar);
        };

    }//GEN-LAST:event_jBtnSad_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgSad_Produtos dialog = new JDlgSad_Produtos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSad_Alterar;
    private javax.swing.JButton jBtnSad_Cancelar;
    private javax.swing.JButton jBtnSad_Confirmar;
    private javax.swing.JButton jBtnSad_Excluir;
    private javax.swing.JButton jBtnSad_Incluir;
    private javax.swing.JButton jBtnSad_Pesquisar;
    private javax.swing.JCheckBox jChbSad_Novo;
    private javax.swing.JCheckBox jChbSad_Testado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxtSad_Codigo;
    private javax.swing.JTextField jTxtSad_Marca;
    private javax.swing.JTextField jTxtSad_Nome;
    private javax.swing.JTextField jTxtSad_Peso;
    private javax.swing.JTextField jTxtSad_Valor;
    // End of variables declaration//GEN-END:variables
}
