/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author SANTIAGO
 */
public class JFrmSad_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmSad_Principal
     */
    public JFrmSad_Principal() {
        initComponents();
        setTitle("Sistema de compras e Vendas");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        Sad_Usuarios = new javax.swing.JButton();
        Sad_Produtos = new javax.swing.JButton();
        Sad_Vendedor = new javax.swing.JButton();
        Sad_ConsultaProdutos = new javax.swing.JButton();
        Sad_ConsultaClientes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastro = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuConsulta = new javax.swing.JMenu();
        jMnuClientes1 = new javax.swing.JMenuItem();
        jMnuUsuarios1 = new javax.swing.JMenuItem();
        jMnuProdutos1 = new javax.swing.JMenuItem();
        jMnuVendedor1 = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        Sad_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/identity.png"))); // NOI18N
        Sad_Usuarios.setFocusable(false);
        Sad_Usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sad_Usuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sad_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sad_UsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(Sad_Usuarios);

        Sad_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/network.png"))); // NOI18N
        Sad_Produtos.setFocusable(false);
        Sad_Produtos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sad_Produtos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sad_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sad_ProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(Sad_Produtos);

        Sad_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator.png"))); // NOI18N
        Sad_Vendedor.setFocusable(false);
        Sad_Vendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sad_Vendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sad_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sad_VendedorActionPerformed(evt);
            }
        });
        jToolBar1.add(Sad_Vendedor);

        Sad_ConsultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        Sad_ConsultaProdutos.setFocusable(false);
        Sad_ConsultaProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sad_ConsultaProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sad_ConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sad_ConsultaProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(Sad_ConsultaProdutos);

        Sad_ConsultaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        Sad_ConsultaClientes.setFocusable(false);
        Sad_ConsultaClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sad_ConsultaClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sad_ConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sad_ConsultaClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(Sad_ConsultaClientes);

        jMnuCadastro.setText("Cadastros");

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuClientes);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/identity.png"))); // NOI18N
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuUsuarios);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/network.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuProdutos);

        jMnuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator.png"))); // NOI18N
        jMnuVendedor.setText("Vendedor");
        jMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuVendedor);
        jMnuCadastro.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuSair);

        jMenuBar1.add(jMnuCadastro);

        jMnuMovimento.setText("Movimento");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas);

        jMenuBar1.add(jMnuMovimento);

        jMnuConsulta.setText("Consulta");

        jMnuClientes1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        jMnuClientes1.setText("Consulta Clientes");
        jMnuClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientes1ActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuClientes1);

        jMnuUsuarios1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        jMnuUsuarios1.setText("Consulta Vendas");
        jMnuUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios1ActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuUsuarios1);

        jMnuProdutos1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/network.png"))); // NOI18N
        jMnuProdutos1.setText("Consulta Produtos");
        jMnuProdutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutos1ActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuProdutos1);

        jMnuVendedor1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator.png"))); // NOI18N
        jMnuVendedor1.setText("Consulta Vendedor");
        jMnuVendedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedor1ActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuVendedor1);

        jMenuBar1.add(jMnuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        JDlgSad_Clientes jDlgClientes = new JDlgSad_Clientes(this, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgSad_Usuarios jDlgUsuarios = new JDlgSad_Usuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        JDlgSad_Produtos jDlgProdutos = new JDlgSad_Produtos(this, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorActionPerformed
        // TODO add your handling code here:
        JDlgSad_Vendedor jDlgVendedor = new JDlgSad_Vendedor(this, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
        JDlgSad_Vendas jDlgVendas = new JDlgSad_Vendas(this, true);
        jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void Sad_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sad_ProdutosActionPerformed
        // TODO add your handling code here:
        jMnuProdutosActionPerformed(null);
    }//GEN-LAST:event_Sad_ProdutosActionPerformed

    private void jMnuClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientes1ActionPerformed
        // TODO add your handling code here:
        JDlgSad_ConsultaClientes jDlgConsultaClientes = new JDlgSad_ConsultaClientes(this, true);
        jDlgConsultaClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientes1ActionPerformed

    private void jMnuProdutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutos1ActionPerformed
        // TODO add your handling code here:
        JDlgSad_ConsultaProdutos jDlgConsultaProdutos = new JDlgSad_ConsultaProdutos(this, true);
        jDlgConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuProdutos1ActionPerformed

    private void jMnuVendedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedor1ActionPerformed
        // TODO add your handling code here:
        JDlgSad_ConsultaVendedor jDlgConsultaVendedor = new JDlgSad_ConsultaVendedor(this, true);
        jDlgConsultaVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVendedor1ActionPerformed

    private void jMnuUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios1ActionPerformed
        // TODO add your handling code here:
        JDlgSad_ConsultaVendas jDlgConsultaVendas = new JDlgSad_ConsultaVendas(this, true);
        jDlgConsultaVendas.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarios1ActionPerformed

    private void Sad_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sad_UsuariosActionPerformed
        // TODO add your handling code here:
        jMnuUsuariosActionPerformed(null);
    }//GEN-LAST:event_Sad_UsuariosActionPerformed

    private void Sad_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sad_VendedorActionPerformed
        // TODO add your handling code here:
        jMnuVendedorActionPerformed(null);
    }//GEN-LAST:event_Sad_VendedorActionPerformed

    private void Sad_ConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sad_ConsultaClientesActionPerformed
        // TODO add your handling code here:
        jMnuClientes1ActionPerformed(null);
    }//GEN-LAST:event_Sad_ConsultaClientesActionPerformed

    private void Sad_ConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sad_ConsultaProdutosActionPerformed
        // TODO add your handling code here:
        jMnuProdutos1ActionPerformed(null);
    }//GEN-LAST:event_Sad_ConsultaProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmSad_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmSad_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmSad_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmSad_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmSad_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sad_ConsultaClientes;
    private javax.swing.JButton Sad_ConsultaProdutos;
    private javax.swing.JButton Sad_Produtos;
    private javax.swing.JButton Sad_Usuarios;
    private javax.swing.JButton Sad_Vendedor;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuCadastro;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuClientes1;
    private javax.swing.JMenu jMnuConsulta;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuProdutos1;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuUsuarios1;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendedor;
    private javax.swing.JMenuItem jMnuVendedor1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
