/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pesquisar;

import java.util.List;
import javax.swing.JOptionPane;
import bean.SadUsuarios;
import dao.SadUsuariosDAO;
import java.io.File;
import javax.swing.JFileChooser;
import tools.Sad_Util;
import view.JDlgSad_Usuarios;
import controller.Sad_ControllerUsuarios;

/**
 *
 * @author u70874542189
 */
public class JDlgSad_UsuariosPesquisar extends javax.swing.JDialog {

    private boolean confirmou = false;

    public boolean ativarBotoes() {
        return confirmou;
    }

    /**
     * Creates new form JDlgUsuariosPesquisar
     */
    private JDlgSad_Usuarios jDlgSad_Usuarios;
    Sad_ControllerUsuarios Sad_ControllerUsuarios;

    public JDlgSad_UsuariosPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pesquisar Usuarios");
        Sad_ControllerUsuarios = new Sad_ControllerUsuarios();
        SadUsuariosDAO sad_UsuariosDAO = new SadUsuariosDAO();
        List lista = (List) sad_UsuariosDAO.listAll();
        Sad_ControllerUsuarios.setList(lista);
        jTblSad_Tabela.setModel(Sad_ControllerUsuarios);
    }

    public void setTelaPai(JDlgSad_Usuarios jDlgSad_Usuarios) {;
        this.jDlgSad_Usuarios = jDlgSad_Usuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelSad_Painel = new javax.swing.JScrollPane();
        jTblSad_Tabela = new javax.swing.JTable();
        jBtnSad_OK = new javax.swing.JButton();
        jBtnSad_Cancelar = new javax.swing.JButton();
        jBtnSad_Exportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTblSad_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblSad_Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblSad_TabelaMouseClicked(evt);
            }
        });
        jScrollPanelSad_Painel.setViewportView(jTblSad_Tabela);

        jBtnSad_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnSad_OK.setText("Ok");
        jBtnSad_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_OKActionPerformed(evt);
            }
        });

        jBtnSad_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnSad_Cancelar.setText("Cancelar");
        jBtnSad_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_CancelarActionPerformed(evt);
            }
        });

        jBtnSad_Exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnSad_Exportar.setText("Exportar");
        jBtnSad_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSad_ExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPanelSad_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSad_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSad_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSad_Exportar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPanelSad_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSad_OK)
                    .addComponent(jBtnSad_Cancelar)
                    .addComponent(jBtnSad_Exportar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSad_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_OKActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTblSad_Tabela.getSelectedRow();
        if (selectedRow >= 0) {
            SadUsuarios sadUsuarios = Sad_ControllerUsuarios.getBean(selectedRow);
            jDlgSad_Usuarios.beanView(sadUsuarios);
            confirmou = true;
            this.setVisible(false);
        } else {
            Sad_Util.sad_mensagem("Selecione um usuário!");
        }

    }//GEN-LAST:event_jBtnSad_OKActionPerformed

    private void jBtnSad_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_CancelarActionPerformed
        // TODO add your handling code here:
        confirmou = false;
        setVisible(false);
    }//GEN-LAST:event_jBtnSad_CancelarActionPerformed

    private void jBtnSad_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSad_ExportarActionPerformed
        // TODO add your handling code here:
        List<SadUsuarios> usuarios = Sad_ControllerUsuarios.getUsuarios();
        if (usuarios == null || usuarios.isEmpty()) {
            Sad_Util.sad_mensagem("Nenhum usuário para exportar!");
            return;
        }

        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Salvar CSV");
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            Sad_ControllerUsuarios.exportar(usuarios, file);
        }
    }//GEN-LAST:event_jBtnSad_ExportarActionPerformed

    private void jTblSad_TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblSad_TabelaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jBtnSad_OKActionPerformed(null);
        }
    }//GEN-LAST:event_jTblSad_TabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_UsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_UsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_UsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgSad_UsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgSad_UsuariosPesquisar dialog = new JDlgSad_UsuariosPesquisar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSad_Cancelar;
    private javax.swing.JButton jBtnSad_Exportar;
    private javax.swing.JButton jBtnSad_OK;
    private javax.swing.JScrollPane jScrollPanelSad_Painel;
    private javax.swing.JTable jTblSad_Tabela;
    // End of variables declaration//GEN-END:variables
}
