package bean;
// Generated 17/09/2025 13:08:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SadClientes generated by hbm2java
 */
@Entity
@Table(name = "sad_clientes", catalog = "db_santiago_mendoza"
)
public class SadClientes implements java.io.Serializable {

    private int sadIdClientes;
    private String sadNome;
    private String sadCpf;
    private String sadRg;
    private int sadSexo;
    private Date sadDataNascimento;
    private String sadEmail;
    private String sadCep;
    private String sadEndereco;
    private String sadBairro;
    private String sadCidade;
    private String sadTelefoneResidencial;
    private String sadCelular;
    private String sadSenha;
    private String sadPronomes;

    public SadClientes() {
    }

    public SadClientes(int sadIdClientes, String sadNome, String sadCpf, String sadRg, int sadSexo, String sadEmail, String sadCep, String sadEndereco, String sadBairro, String sadCidade, String sadCelular, String sadSenha) {
        this.sadIdClientes = sadIdClientes;
        this.sadNome = sadNome;
        this.sadCpf = sadCpf;
        this.sadRg = sadRg;
        this.sadSexo = sadSexo;
        this.sadEmail = sadEmail;
        this.sadCep = sadCep;
        this.sadEndereco = sadEndereco;
        this.sadBairro = sadBairro;
        this.sadCidade = sadCidade;
        this.sadCelular = sadCelular;
        this.sadSenha = sadSenha;
    }

    public SadClientes(int sadIdClientes, String sadNome, String sadCpf, String sadRg, int sadSexo, Date sadDataNascimento, String sadEmail, String sadCep, String sadEndereco, String sadBairro, String sadCidade, String sadTelefoneResidencial, String sadCelular, String sadSenha, String sadPronomes, Set sadVendases) {
        this.sadIdClientes = sadIdClientes;
        this.sadNome = sadNome;
        this.sadCpf = sadCpf;
        this.sadRg = sadRg;
        this.sadSexo = sadSexo;
        this.sadDataNascimento = sadDataNascimento;
        this.sadEmail = sadEmail;
        this.sadCep = sadCep;
        this.sadEndereco = sadEndereco;
        this.sadBairro = sadBairro;
        this.sadCidade = sadCidade;
        this.sadTelefoneResidencial = sadTelefoneResidencial;
        this.sadCelular = sadCelular;
        this.sadSenha = sadSenha;
        this.sadPronomes = sadPronomes;
    }

    @Id

    @Column(name = "sad_idClientes", unique = true, nullable = false)
    public int getSadIdClientes() {
        return this.sadIdClientes;
    }

    public void setSadIdClientes(int sadIdClientes) {
        this.sadIdClientes = sadIdClientes;
    }

    @Column(name = "sad_nome", nullable = false, length = 100)
    public String getSadNome() {
        return this.sadNome;
    }

    public void setSadNome(String sadNome) {
        this.sadNome = sadNome;
    }

    @Column(name = "sad_cpf", nullable = false, length = 14)
    public String getSadCpf() {
        return this.sadCpf;
    }

    public void setSadCpf(String sadCpf) {
        this.sadCpf = sadCpf;
    }

    @Column(name = "sad_rg", nullable = false, length = 12)
    public String getSadRg() {
        return this.sadRg;
    }

    public void setSadRg(String sadRg) {
        this.sadRg = sadRg;
    }

    @Column(name = "sad_sexo", nullable = false)
    public int getSadSexo() {
        return this.sadSexo;
    }

    public void setSadSexo(int sadSexo) {
        this.sadSexo = sadSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sad_dataNascimento", length = 10)
    public Date getSadDataNascimento() {
        return this.sadDataNascimento;
    }

    public void setSadDataNascimento(Date sadDataNascimento) {
        this.sadDataNascimento = sadDataNascimento;
    }

    @Column(name = "sad_email", nullable = false, length = 80)
    public String getSadEmail() {
        return this.sadEmail;
    }

    public void setSadEmail(String sadEmail) {
        this.sadEmail = sadEmail;
    }

    @Column(name = "sad_cep", nullable = false, length = 9)
    public String getSadCep() {
        return this.sadCep;
    }

    public void setSadCep(String sadCep) {
        this.sadCep = sadCep;
    }

    @Column(name = "sad_endereco", nullable = false, length = 50)
    public String getSadEndereco() {
        return this.sadEndereco;
    }

    public void setSadEndereco(String sadEndereco) {
        this.sadEndereco = sadEndereco;
    }

    @Column(name = "sad_bairro", nullable = false, length = 30)
    public String getSadBairro() {
        return this.sadBairro;
    }

    public void setSadBairro(String sadBairro) {
        this.sadBairro = sadBairro;
    }

    @Column(name = "sad_cidade", nullable = false, length = 50)
    public String getSadCidade() {
        return this.sadCidade;
    }

    public void setSadCidade(String sadCidade) {
        this.sadCidade = sadCidade;
    }

    @Column(name = "sad_telefoneResidencial", length = 10)
    public String getSadTelefoneResidencial() {
        return this.sadTelefoneResidencial;
    }

    public void setSadTelefoneResidencial(String sadTelefoneResidencial) {
        this.sadTelefoneResidencial = sadTelefoneResidencial;
    }

    @Column(name = "sad_celular", nullable = false, length = 15)
    public String getSadCelular() {
        return this.sadCelular;
    }

    public void setSadCelular(String sadCelular) {
        this.sadCelular = sadCelular;
    }

    @Column(name = "sad_senha", nullable = false, length = 30)
    public String getSadSenha() {
        return this.sadSenha;
    }

    public void setSadSenha(String sadSenha) {
        this.sadSenha = sadSenha;
    }

    @Column(name = "sad_pronomes", length = 8)
    public String getSadPronomes() {
        return this.sadPronomes;
    }

    public void setSadPronomes(String sadPronomes) {
        this.sadPronomes = sadPronomes;
    }

    @Override
    public String toString() {
        return this.sadNome;
    }
    @Override
    public boolean equals(Object object) {
        if (object instanceof SadClientes) {
            SadClientes sadClientes = (SadClientes) object;
            if (this.getSadIdClientes() == sadClientes.getSadIdClientes()) {
                return true;
            }
        }
        return false;
    }

}
