package bean;
// Generated 17/09/2025 13:08:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SadProdutos generated by hbm2java
 */
@Entity
@Table(name = "sad_produtos", catalog = "db_santiago_mendoza"
)
public class SadProdutos implements java.io.Serializable {

    private int sadIdProdutos;
    private String sadPeso;
    private double sadValor;
    private String sadNome;
    private String sadTestado;
    private String sadNovo;
    private String sadMarca;

    public SadProdutos() {
    }

    public SadProdutos(int sadIdProdutos, String sadPeso, double sadValor, String sadNome, String sadTestado, String sadNovo, String sadMarca) {
        this.sadIdProdutos = sadIdProdutos;
        this.sadPeso = sadPeso;
        this.sadValor = sadValor;
        this.sadNome = sadNome;
        this.sadTestado = sadTestado;
        this.sadNovo = sadNovo;
        this.sadMarca = sadMarca;
    }

    @Id

    @Column(name = "sad_idProdutos", unique = true, nullable = false)
    public int getSadIdProdutos() {
        return this.sadIdProdutos;
    }

    public void setSadIdProdutos(int sadIdProdutos) {
        this.sadIdProdutos = sadIdProdutos;
    }

    @Column(name = "sad_peso", nullable = false, length = 4)
    public String getSadPeso() {
        return this.sadPeso;
    }

    public void setSadPeso(String sadPeso) {
        this.sadPeso = sadPeso;
    }

    @Column(name = "sad_valor", nullable = false, length = 4)
    public double getSadValor() {
        return this.sadValor;
    }

    public void setSadValor(double sadValor) {
        this.sadValor = sadValor;
    }

    @Column(name = "sad_nome", nullable = false, length = 50)
    public String getSadNome() {
        return this.sadNome;
    }

    public void setSadNome(String sadNome) {
        this.sadNome = sadNome;
    }

    @Column(name = "sad_testado", nullable = false, length = 1)
    public String getSadTestado() {
        return this.sadTestado;
    }

    public void setSadTestado(String sadTestado) {
        this.sadTestado = sadTestado;
    }

    @Column(name = "sad_novo", nullable = false, length = 1)
    public String getSadNovo() {
        return this.sadNovo;
    }

    public void setSadNovo(String sadNovo) {
        this.sadNovo = sadNovo;
    }

    @Column(name = "sad_marca", nullable = false, length = 40)
    public String getSadMarca() {
        return this.sadMarca;
    }

    public void setSadMarca(String sadMarca) {
        this.sadMarca = sadMarca;
    }
    @Override
    public String toString() {
        return this.sadNome;
    }
    @Override
    public boolean equals(Object object) {
        if (object instanceof SadProdutos) {
            SadProdutos sadProdutos = (SadProdutos) object;
            if (this.getSadIdProdutos() == sadProdutos.getSadIdProdutos()) {
                return true;
            }
        }
        return false;
    }

}
