package bean;
// Generated 17/09/2025 13:08:25 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SadUsuarios generated by hbm2java
 */
@Entity
@Table(name = "sad_usuarios", catalog = "db_santiago_mendoza"
)
public class SadUsuarios implements java.io.Serializable {

    private int sadIdUsuarios;
    private String sadNome;
    private String sadApelido;
    private String sadCpf;
    private Date sadDataNascimento;
    private String sadSenha;
    private int sadNivel;
    private String sadAtivo;

    public SadUsuarios() {
    }

    public SadUsuarios(int sadIdUsuarios, String sadNome, String sadApelido, String sadCpf, String sadSenha, int sadNivel, String sadAtivo) {
        this.sadIdUsuarios = sadIdUsuarios;
        this.sadNome = sadNome;
        this.sadApelido = sadApelido;
        this.sadCpf = sadCpf;
        this.sadSenha = sadSenha;
        this.sadNivel = sadNivel;
        this.sadAtivo = sadAtivo;
    }

    public SadUsuarios(int sadIdUsuarios, String sadNome, String sadApelido, String sadCpf, Date sadDataNascimento, String sadSenha, int sadNivel, String sadAtivo) {
        this.sadIdUsuarios = sadIdUsuarios;
        this.sadNome = sadNome;
        this.sadApelido = sadApelido;
        this.sadCpf = sadCpf;
        this.sadDataNascimento = sadDataNascimento;
        this.sadSenha = sadSenha;
        this.sadNivel = sadNivel;
        this.sadAtivo = sadAtivo;
    }

    @Id

    @Column(name = "sad_idUsuarios", unique = true, nullable = false)
    public int getSadIdUsuarios() {
        return this.sadIdUsuarios;
    }

    public void setSadIdUsuarios(int sadIdUsuarios) {
        this.sadIdUsuarios = sadIdUsuarios;
    }

    @Column(name = "sad_nome", nullable = false, length = 50)
    public String getSadNome() {
        return this.sadNome;
    }

    public void setSadNome(String sadNome) {
        this.sadNome = sadNome;
    }

    @Column(name = "sad_apelido", nullable = false, length = 25)
    public String getSadApelido() {
        return this.sadApelido;
    }

    public void setSadApelido(String sadApelido) {
        this.sadApelido = sadApelido;
    }

    @Column(name = "sad_cpf", nullable = false, length = 14)
    public String getSadCpf() {
        return this.sadCpf;
    }

    public void setSadCpf(String sadCpf) {
        this.sadCpf = sadCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sad_dataNascimento", length = 10)
    public Date getSadDataNascimento() {
        return this.sadDataNascimento;
    }

    public void setSadDataNascimento(Date sadDataNascimento) {
        this.sadDataNascimento = sadDataNascimento;
    }

    @Column(name = "sad_senha", nullable = false, length = 20)
    public String getSadSenha() {
        return this.sadSenha;
    }

    public void setSadSenha(String sadSenha) {
        this.sadSenha = sadSenha;
    }

    @Column(name = "sad_nivel", nullable = false)
    public int getSadNivel() {
        return this.sadNivel;
    }

    public void setSadNivel(int sadNivel) {
        this.sadNivel = sadNivel;
    }

    @Column(name = "sad_ativo", nullable = false, length = 1)
    public String getSadAtivo() {
        return this.sadAtivo;
    }

    public void setSadAtivo(String sadAtivo) {
        this.sadAtivo = sadAtivo;
    }

}
