package bean;
// Generated 17/09/2025 13:08:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SadVendedor generated by hbm2java
 */
@Entity
@Table(name = "sad_vendedor", catalog = "db_santiago_mendoza"
)
public class SadVendedor implements java.io.Serializable {

    private int sadIdVendedor;
    private String sadNome;
    private String sadSenha;
    private Date sadDataNascimento;
    private String sadQuantidadeVendas;
    private double sadArrecadado;
    private String sadCelular;

    public SadVendedor() {
    }

    public SadVendedor(int sadIdVendedor, String sadNome, String sadSenha, String sadQuantidadeVendas, String sadCelular) {
        this.sadIdVendedor = sadIdVendedor;
        this.sadNome = sadNome;
        this.sadSenha = sadSenha;
        this.sadQuantidadeVendas = sadQuantidadeVendas;
        this.sadCelular = sadCelular;
    }

    public SadVendedor(int sadIdVendedor, String sadNome, String sadSenha, Date sadDataNascimento, String sadQuantidadeVendas, double sadArrecadado, String sadCelular) {
        this.sadIdVendedor = sadIdVendedor;
        this.sadNome = sadNome;
        this.sadSenha = sadSenha;
        this.sadDataNascimento = sadDataNascimento;
        this.sadQuantidadeVendas = sadQuantidadeVendas;
        this.sadArrecadado = sadArrecadado;
        this.sadCelular = sadCelular;
    }

    @Id

    @Column(name = "sad_idVendedor", unique = true, nullable = false)
    public int getSadIdVendedor() {
        return this.sadIdVendedor;
    }

    public void setSadIdVendedor(int sadIdVendedor) {
        this.sadIdVendedor = sadIdVendedor;
    }

    @Column(name = "sad_nome", nullable = false, length = 50)
    public String getSadNome() {
        return this.sadNome;
    }

    public void setSadNome(String sadNome) {
        this.sadNome = sadNome;
    }

    @Column(name = "sad_senha", nullable = false, length = 30)
    public String getSadSenha() {
        return this.sadSenha;
    }

    public void setSadSenha(String sadSenha) {
        this.sadSenha = sadSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sad_dataNascimento", length = 10)
    public Date getSadDataNascimento() {
        return this.sadDataNascimento;
    }

    public void setSadDataNascimento(Date sadDataNascimento) {
        this.sadDataNascimento = sadDataNascimento;
    }

    @Column(name = "sad_quantidadeVendas", nullable = false, length = 10)
    public String getSadQuantidadeVendas() {
        return this.sadQuantidadeVendas;
    }

    public void setSadQuantidadeVendas(String sadQuantidadeVendas) {
        this.sadQuantidadeVendas = sadQuantidadeVendas;
    }

    @Column(name = "sad_arrecadado", precision = 15)
    public double getSadArrecadado() {
        return this.sadArrecadado;
    }

    public void setSadArrecadado(double sadArrecadado) {
        this.sadArrecadado = sadArrecadado;
    }

    @Column(name = "sad_celular", nullable = false, length = 15)
    public String getSadCelular() {
        return this.sadCelular;
    }

    public void setSadCelular(String sadCelular) {
        this.sadCelular = sadCelular;
    }

    @Override
    public String toString() {
        return this.sadNome;
    }
    @Override
    public boolean equals(Object object) {
        if (object instanceof SadVendedor) {
            SadVendedor sadVendedor = (SadVendedor) object;
            if (this.getSadIdVendedor() == sadVendedor.getSadIdVendedor()) {
                return true;
            }
        }
        return false;
    }

}
