package bean;
// Generated 17/09/2025 13:08:25 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SadVendaProdutos generated by hbm2java
 */
@Entity
@Table(name = "sad_vendaProdutos", catalog = "db_santiago_mendoza"
)
public class SadVendaProdutos implements java.io.Serializable {

    private int sadIdVendaProdutos;
    private SadProdutos sadProdutos;
    private SadVendas sadVendas;
    private int sadQuantidade;
    private double sadValorUnitario;

    public SadVendaProdutos() {
    }

    public SadVendaProdutos(int sadIdVendaProdutos, SadProdutos sadProdutos, SadVendas sadVendas, int sadQuantidade, double sadValorUnitario) {
        this.sadIdVendaProdutos = sadIdVendaProdutos;
        this.sadProdutos = sadProdutos;
        this.sadVendas = sadVendas;
        this.sadQuantidade = sadQuantidade;
        this.sadValorUnitario = sadValorUnitario;
    }

    @Id

    @Column(name = "sad_idVendaProdutos", unique = true, nullable = false)
    public int getSadIdVendaProdutos() {
        return this.sadIdVendaProdutos;
    }

    public void setSadIdVendaProdutos(int sadIdVendaProdutos) {
        this.sadIdVendaProdutos = sadIdVendaProdutos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sad_fkProdutos", nullable = false)
    public SadProdutos getSadProdutos() {
        return this.sadProdutos;
    }

    public void setSadProdutos(SadProdutos sadProdutos) {
        this.sadProdutos = sadProdutos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sad_fkVendas", nullable = false)
    public SadVendas getSadVendas() {
        return this.sadVendas;
    }

    public void setSadVendas(SadVendas sadVendas) {
        this.sadVendas = sadVendas;
    }

    @Column(name = "sad_quantidade", nullable = false)
    public int getSadQuantidade() {
        return this.sadQuantidade;
    }

    public void setSadQuantidade(int sadQuantidade) {
        this.sadQuantidade = sadQuantidade;
    }

    @Column(name = "sad_valorUnitario", nullable = false, precision = 10)
    public double getSadValorUnitario() {
        return this.sadValorUnitario;
    }

    public void setSadValorUnitario(double sadValorUnitario) {
        this.sadValorUnitario = sadValorUnitario;
    }

}
