package bean;
// Generated 17/09/2025 13:08:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SadVendas generated by hbm2java
 */
@Entity
@Table(name = "sad_vendas", catalog = "db_santiago_mendoza"
)
public class SadVendas implements java.io.Serializable {

    private int sadIdVendas;
    private SadClientes sadClientes;
    private SadVendedor sadVendedor;
    private Date sadDataVendas;
    private double sadTotal;

    public SadVendas() {
    }

    public SadVendas(int sadIdVendas, Date sadDataVendas, double sadTotal) {
        this.sadIdVendas = sadIdVendas;
        this.sadDataVendas = sadDataVendas;
        this.sadTotal = sadTotal;
    }

    public SadVendas(int sadIdVendas, SadClientes sadClientes, SadVendedor sadVendedor, Date sadDataVendas, double sadTotal) {
        this.sadIdVendas = sadIdVendas;
        this.sadClientes = sadClientes;
        this.sadVendedor = sadVendedor;
        this.sadDataVendas = sadDataVendas;
        this.sadTotal = sadTotal;

    }

    @Id

    @Column(name = "sad_idVendas", unique = true, nullable = false)
    public int getSadIdVendas() {
        return this.sadIdVendas;
    }

    public void setSadIdVendas(int sadIdVendas) {
        this.sadIdVendas = sadIdVendas;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sad_fkClientes")
    public SadClientes getSadClientes() {
        return this.sadClientes;
    }

    public void setSadClientes(SadClientes sadClientes) {
        this.sadClientes = sadClientes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sad_fkVendedor")
    public SadVendedor getSadVendedor() {
        return this.sadVendedor;
    }

    public void setSadVendedor(SadVendedor sadVendedor) {
        this.sadVendedor = sadVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sad_dataVendas", nullable = false, length = 10)
    public Date getSadDataVendas() {
        return this.sadDataVendas;
    }

    public void setSadDataVendas(Date sadDataVendas) {
        this.sadDataVendas = sadDataVendas;
    }

    @Column(name = "sad_total", nullable = false, precision = 10)
    public double getSadTotal() {
        return this.sadTotal;
    }

    public void setSadTotal(double sadTotal) {
        this.sadTotal = sadTotal;
    }
}
